version: '3.7'

services: 
  php:
    environment:
      APP_ENV: preprod
    deploy:
      replicas: 1
      placement:
        preferences:
          - spread: node.role.worker
        constraints:
          - "node.labels.environment==preprod"
      resources:
        limits:
          memory: 300M
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    networks:
      - default
      - traefik-public
    deploy:
      replicas: 1
      placement:
        preferences:
          - spread: node.role.worker
        constraints:
          - "node.labels.environment==preprod"
      resources:
        limits:
          memory: 128M
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.demosymfo-http.rule=Host(`demosymfo.genilink.com`)"
        - "traefik.http.routers.demosymfo-http.entrypoints=http"
        - "traefik.http.routers.demosymfo-http.middlewares=https-redirect"
        - "traefik.http.routers.demosymfo-https.rule=Host(`demosymfo.genilink.com`)"
        - "traefik.http.routers.demosymfo-https.entrypoints=https"
        - "traefik.http.routers.demosymfo-https.tls=true"
        - "traefik.http.routers.demosymfo-https.tls.certresolver=le"
        - "traefik.http.services.demosymfo.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
